# This is a basic workflow to help you get started with Actions

name: build js files for screeps

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build release files
      run: |
        sh gradlew clean build
    - name: add build files to release folder
      run: |
        mkdir release
        rm -r build/js/packages_imported/kotlin-test
        rm -r build/js/packages_imported/kotlin-test-js-runner
        cp build/js/packages/main/kotlin/main.js release
        find build/js/packages_imported -name \*.js -exec cp {} release \;
    - name: stage changed files
      run: git add *
    - name: commit changed files
      run: |
        git config --local user.name "builderbot"
        git commit --allow-empty -m "add new release files"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true